### ISSUE TITLE
Versioning of the installer

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack-windows-installer#4] opened 2016-04-26 02:38 UTC
Should we follow the same version number as the Hack release?  Is this confusing to have a separate version scheme for the installer itself?

**Comment by texhex** [comment] 2016-04-26 04:54
Good idea, this would make it easier for the user to detect which version they are using. But because the installer might be updated independently from the fonts, I would add a patch/build number. So the next release would be 2.020.1. If I change the installer while we are still deploying 2.020, it would be 2.020.2. The guys from semver.org will hate us for this, but anything for the user ;-).

The only time this versioning would implode is when there will be a another Hack font family, e.g. "Hack Sans". Is this something that will happen in the near future?

**Comment by chrissimpkins** [comment] 2016-04-26 11:16
Possible. It was just a thought.  Since we will be linking it for download on the README and website, perhaps it is not necessary.

**Comment by texhex** [comment] 2016-04-26 15:57
OK, I will keep this issue open for now. If nobody thinks this is necessary, I will close it with WONTFIX in a few weeks.

**Comment by chrissimpkins** [comment] 2016-04-26 16:29
@texhex Sounds great.  Thanks!

**Comment by texhex** [comment] 2016-04-28 08:21
One additional information. Although we display the version number inside the installer, so the user knows which version of Hack is about to be installed, this information is lost when the user checks the information in Add/Remove programs. So from just looking at this entry, he/she has no chance to detect which version of Hack is actually installed. 

This could only be fixed with two options:

- Synchronizing the version of the installer and Hack, as you have proposed. Version/Product version would then match perfectly the Hack version number. But this will be a problem when I release a newer version of the setup. In this case I could only add something to the version number (e.g. a second release would then be 2.020.2 which might confuse users as well.

- Adding the version of Hack to the name of the application, e.g. "Hack v2.020 Windows Installer". This can be easily done in Inno Setup by using `UninstallDisplayName` The problem is, the Version (column) and the product version would still say v1.1.2 which is again confusing. 

![add-remove programs entry](https://cloud.githubusercontent.com/assets/2500900/14879540/16ce817a-0d2a-11e6-9549-a7a495aa79d1.PNG)

**Comment by chrissimpkins** [comment] 2016-04-28 10:46
They can use Add/Remove Programs to remove the fonts?  Can you show me a screenshot?

**Comment by texhex** [comment] 2016-04-28 11:02
To be honest, there is not much so see. 

The user click on "Uninstall" and a message box asks "Are you sure?". If the user clicks on Yes, the original installer comes up (but does not require user interaction) and will show a progress bar while it removes all files. At the end, the user requested to restart the machine. That's all. 

![uninstall](https://cloud.githubusercontent.com/assets/2500900/14883878/552f0c34-0d41-11e6-9d3a-7c8b6667c48d.PNG)

**Comment by chrissimpkins** [comment] 2016-04-28 12:37
I see.  Can users view the font version in a font preview application if we need their installed version number?  For instance on OS X, I see this in Font Book for Hack:

<img width="768" alt="hack-versioning" src="https://cloud.githubusercontent.com/assets/4249591/14885888/f1a5a3b4-0d1b-11e6-8780-fe4f80f52c1d.png">

Overall, I think that this is less important for us because an uninstall means that they are abandoning the fonts and I can't think of a circumstance where they *should* care what version they are uninstalling.  The goal will be to encourage all upgrades to take place through the installer and avoid the need to uninstall altogether if the user intends to maintain the fonts on their system.  Can you think of a situation where they might want to know what version they are removing?

**Comment by texhex** [comment] 2016-04-28 15:40
Yes, you can see this information also in Windows. Control Panel -> Appearance and Personalization-> Open Hack "Folder" -> Double click a font.

![font preview](https://cloud.githubusercontent.com/assets/2500900/14891715/1533073a-0d68-11e6-82f1-7fb838944662.PNG)

And the version is rather not used when a user abandons the font, but rather to get the information "Which version are you using". But on the other hand, he/she can also get this from the Fonts applet.

**Comment by chrissimpkins** [comment] 2016-04-29 00:01
I think that this is sufficient.  This is pretty straightforward and shouldn't influence your versioning in the tool IMO.

**Comment by texhex** [comment] 2016-05-01 13:34
Good point. And if the user checks the version of the installed through the Fonts Applet instead of the version that is displayed in Add/Remove programs, we can be sure he is actually using that version. When checking the installer, it does not take into account when a new version was manually installed. Or, for example he has also used OSFontPack which installed an older version.

Discussed and decided, I will also this issue.

**Closed** 2016-05-01 13:34 UTC

**Comment by chrissimpkins** [comment] 2016-05-01 14:26
thanks @texhex
