### ISSUE TITLE
installer stuck at starting fontcache on windows 10 Version	10.0.15063 Build 15063

### ISSUE THREAD

**Issue by dev-seahouse** [source-foundry/Hack-windows-installer#11] opened 2017-05-16 14:59 UTC
![image](https://cloud.githubusercontent.com/assets/4751342/26112669/210a2ff6-3a8b-11e7-835c-f12de0507249.png)

**Comment by dev-seahouse** [comment] 2017-05-16 15:01
![image](https://cloud.githubusercontent.com/assets/4751342/26112838/8802c5d8-3a8b-11e7-9fe4-a03232b6fe49.png)

**Comment by texhex** [comment] 2017-05-16 18:25
Thanks for that, I will check the code once more what is going wrong there. 

For some reasons a single SCxxx call doesn't return so the setup hangs. I still have no idea how I could possible debug this.

**Comment by shadeofsound** [comment] 2017-06-12 16:00
Hello, I've encountered this same issue. Upon analyzing the wait chains involved (using the Win10 Task Manager) with the HackWindowsInstaller.exe process, I found that Microsoft Office-related programs were causing the process to enter a 'Non-Responsive' state (e.g. WINWORD.exe, lync.exe, Teams.exe). After terminating the processes related and closing the related programs, the installer proceeded normally. Can you check, @dev-seahouse, and see if performing these actions resolves your service start hang issue?

If so, I would recommend that either a disclaimer be placed in the installation instructions, the git README.md, or if feasible, a check be written into the installer to address these related processes and prompt for user action.

**Comment by texhex** [comment] 2017-06-12 17:53
Thanks @shadeofsound, if this is confirmed by other having the issue I'm more to happy to add at least a note. I will also check if it's possible to check for the process names.

**Comment by harrypei** [comment] 2017-06-23 10:15
the same to me...
no responsive 
win10 64bit

**Comment by jyfradet** [comment] 2017-06-27 14:07
Same problem in Windows 7 Professionnal. Not specific to Win10.

**Comment by jyfradet** [comment] 2017-06-27 14:27
I confirm that on Win7 Pro, closing all applications Microsoft related solved the installer problem... Went super fast and smooth...

**Comment by chrissimpkins** [comment] 2017-06-27 14:41
@jyfradet thanks for the feedback!

@texhex any idea what might be causing this Tex?

**Comment by texhex** [comment] 2017-07-11 17:34
@jyfradet Thanks for the test, so this is clearly Office related. I just tried the third machine, running Word and Excel and executing the installer and... Nothing. Just wend through. 

I will check with the base script over at https://github.com/source-foundry/FSCW/ if it makes a difference when using a document that actually uses Hack.

**Comment by hellectronic** [comment] 2017-07-21 07:01
I can confirm the issue. New Win 10 installation. After reading this and closing Outlook, the Hack setup went through.

**Comment by texhex** [comment] 2017-09-04 19:03
I might have an idea to "fix" this, but this needs testing in the wild before. We will test the new procedure with the DEV installer for Hack. 

If it works there, we will change it for the release installer as well.

**Comment by chrissimpkins** [comment] 2017-09-04 20:47
Let me know if you need a new set of fonts with a different name to test this @texhex.  If you are good with very early dev releases of the v3 fonts that do not include changes to the name of the typeface, they are currently available on the path `build/ttf/Hack-*.ttf` in the `dev-build-scripts` branch of the repository.

**Comment by Clast** [comment] 2017-09-18 02:26
Few other applications seem to block it as well. Blizzard's Battle.net Agent.exe also causes it to hang. 

Closing it resolves it.

**Comment by texhex** [comment] 2017-10-08 15:03
@Clast @hellectronic Thanks for the reports. We are currently trying to figure out how to get the Hack DEV/TEST fonts right which would allow us to create a Windows installer for Hack that can be installed beside the release ones. If that installer turns out to be working and no longer shows this bug, the 3.0 will have the fixed version from the start.

**Comment by texhex** [comment] 2017-10-21 08:54
@dev-seahouse @shadeofsound @harrypei @jyfradet @hellectronic @Clast 

First, thank you for your patience. I'm 99% sure I found the issue and it is fixed in the current version - it should no longer happen when using v1.4.1 onwards (Hack v3.000). You will be able to download in about 20-30 minutes.

Long explanation: After trying to fix it some days ago because I finally had a PC where I could reproduce it, I believed this was caused when starting the .NET Font Cache service. This was incorrect, the issue happened a line below this step when the [WM_FONTCHANGE]( https://msdn.microsoft.com/en-us/library/windows/desktop/dd145211(v=vs.85).aspx) Windows message is sent. 

However, there was no progress display for this step, so the message still showed “Starting service” while the execution has already moved forward. 

For whatever reason, depending on the configuration or running programs, sending this message as a broadcast can hang the installer. It doesn’t seem to happen when sending it from a different program. I have no idea why it only happens on some machines and even there not always. The only idea I have is that the installer receives this message also and can (in some cases) not handle it because it is busy sending the message itself. 

Removing this message from the installer should not have any negative impact as we request a restart anyway.

**Comment by hellectronic** [comment] 2017-10-25 15:27
Today I had the chance to install it on a new windows 10 with a running Outlook. Worked for me, thanks!

**Comment by texhex** [comment] 2017-10-28 13:15
@hellectronic Thanks, good to hear!

**Comment by texhex** [comment] 2017-12-20 14:50
As no new reports came in about this bug, I'm assuming it's fixed for good. Closing this issue.

**Closed by texhex** 2017-12-20 14:50 UTC
